"""initial migration

Revision ID: 1fcbcfa9a20d
Revises: 
Create Date: 2025-02-20 17:40:25.713859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fcbcfa9a20d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.Column('stats_title', sa.String(length=200), nullable=True),
    sa.Column('stats_content', sa.Text(), nullable=True),
    sa.Column('stats_items', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('contact_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('google_maps_embed', sa.Text(), nullable=True),
    sa.Column('working_hours', sa.Text(), nullable=True),
    sa.Column('social_media', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('menu_type', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('permission', sa.String(length=50), nullable=True),
    sa.Column('css_class', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], name='fk_menu_parent', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('client', sa.String(length=200), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('technologies', sa.String(length=200), nullable=True),
    sa.Column('project_url', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_title', sa.String(length=100), nullable=True),
    sa.Column('site_description', sa.Text(), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('favicon_path', sa.String(length=255), nullable=True),
    sa.Column('navbar_bg_color', sa.String(length=7), nullable=True),
    sa.Column('navbar_text_color', sa.String(length=7), nullable=True),
    sa.Column('navbar_active_color', sa.String(length=7), nullable=True),
    sa.Column('navbar_hover_color', sa.String(length=7), nullable=True),
    sa.Column('navbar_is_fixed', sa.Boolean(), nullable=True),
    sa.Column('navbar_is_transparent', sa.Boolean(), nullable=True),
    sa.Column('body_bg_color', sa.String(length=7), nullable=True),
    sa.Column('body_text_color', sa.String(length=7), nullable=True),
    sa.Column('body_link_color', sa.String(length=7), nullable=True),
    sa.Column('body_font_family', sa.String(length=50), nullable=True),
    sa.Column('body_font_size', sa.String(length=10), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('is_dark_mode', sa.Boolean(), nullable=True),
    sa.Column('enable_animations', sa.Boolean(), nullable=True),
    sa.Column('banner_bg_color', sa.String(length=7), nullable=True),
    sa.Column('banner_title_color', sa.String(length=7), nullable=True),
    sa.Column('banner_text_color', sa.String(length=7), nullable=True),
    sa.Column('banner_button_bg_color', sa.String(length=7), nullable=True),
    sa.Column('banner_button_text_color', sa.String(length=7), nullable=True),
    sa.Column('banner_indicator_color', sa.String(length=7), nullable=True),
    sa.Column('about_bg_color', sa.String(length=7), nullable=True),
    sa.Column('about_title_color', sa.String(length=7), nullable=True),
    sa.Column('about_text_color', sa.String(length=7), nullable=True),
    sa.Column('about_stats_number_color', sa.String(length=7), nullable=True),
    sa.Column('about_stats_text_color', sa.String(length=7), nullable=True),
    sa.Column('about_box_bg_color', sa.String(length=7), nullable=True),
    sa.Column('services_bg_color', sa.String(length=7), nullable=True),
    sa.Column('services_title_color', sa.String(length=7), nullable=True),
    sa.Column('services_card_bg_color', sa.String(length=7), nullable=True),
    sa.Column('services_icon_color', sa.String(length=7), nullable=True),
    sa.Column('services_card_title_color', sa.String(length=7), nullable=True),
    sa.Column('services_card_text_color', sa.String(length=7), nullable=True),
    sa.Column('blog_bg_color', sa.String(length=7), nullable=True),
    sa.Column('blog_title_color', sa.String(length=7), nullable=True),
    sa.Column('blog_card_bg_color', sa.String(length=7), nullable=True),
    sa.Column('blog_date_color', sa.String(length=7), nullable=True),
    sa.Column('blog_post_title_color', sa.String(length=7), nullable=True),
    sa.Column('blog_excerpt_color', sa.String(length=7), nullable=True),
    sa.Column('contact_bg_color', sa.String(length=7), nullable=True),
    sa.Column('contact_title_color', sa.String(length=7), nullable=True),
    sa.Column('contact_text_color', sa.String(length=7), nullable=True),
    sa.Column('contact_form_bg_color', sa.String(length=7), nullable=True),
    sa.Column('contact_button_bg_color', sa.String(length=7), nullable=True),
    sa.Column('contact_button_text_color', sa.String(length=7), nullable=True),
    sa.Column('video_bg_color', sa.String(length=7), nullable=True),
    sa.Column('video_title_color', sa.String(length=7), nullable=True),
    sa.Column('video_play_button_color', sa.String(length=7), nullable=True),
    sa.Column('video_overlay_color', sa.String(length=7), nullable=True),
    sa.Column('video_overlay_opacity', sa.Integer(), nullable=True),
    sa.Column('footer_bg_color', sa.String(length=7), nullable=True),
    sa.Column('footer_text_color', sa.String(length=7), nullable=True),
    sa.Column('footer_link_color', sa.String(length=7), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('custom_js', sa.Text(), nullable=True),
    sa.Column('slider_height', sa.Integer(), nullable=True),
    sa.Column('slider_transition_speed', sa.Integer(), nullable=True),
    sa.Column('slider_animation_speed', sa.Integer(), nullable=True),
    sa.Column('slider_is_autoplay', sa.Boolean(), nullable=True),
    sa.Column('slider_show_arrows', sa.Boolean(), nullable=True),
    sa.Column('slider_show_bullets', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('facebook_url', sa.String(length=200), nullable=True),
    sa.Column('twitter_url', sa.String(length=200), nullable=True),
    sa.Column('instagram_url', sa.String(length=200), nullable=True),
    sa.Column('theme_version', sa.String(length=10), nullable=True),
    sa.Column('theme_name', sa.String(length=50), nullable=True),
    sa.Column('is_customized', sa.Boolean(), nullable=True),
    sa.Column('success_color', sa.String(length=10), nullable=False),
    sa.Column('info_color', sa.String(length=10), nullable=False),
    sa.Column('warning_color', sa.String(length=10), nullable=False),
    sa.Column('danger_color', sa.String(length=10), nullable=False),
    sa.Column('navbar_font_family', sa.String(length=50), nullable=True),
    sa.Column('navbar_font_size', sa.String(length=10), nullable=True),
    sa.Column('body_line_height', sa.String(length=10), nullable=True),
    sa.Column('footer_font_family', sa.String(length=50), nullable=True),
    sa.Column('footer_font_size', sa.String(length=10), nullable=True),
    sa.Column('footer_about', sa.Text(), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('maintenance_message', sa.Text(), nullable=True),
    sa.Column('google_analytics_id', sa.String(length=50), nullable=True),
    sa.Column('recaptcha_site_key', sa.String(length=100), nullable=True),
    sa.Column('recaptcha_secret_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=200), nullable=False),
    sa.Column('button_text', sa.String(length=50), nullable=True),
    sa.Column('button_url', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('linkedin_url', sa.String(length=200), nullable=True),
    sa.Column('github_url', sa.String(length=200), nullable=True),
    sa.Column('twitter_url', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('client_title', sa.String(length=100), nullable=True),
    sa.Column('client_company', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('folder_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('screenshot_url', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=1024), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('video_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('thumbnail', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('featured_image', sa.String(length=200), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('shipping_method', sa.String(length=50), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('contents')
    op.drop_table('blog_posts')
    op.drop_table('activity_logs')
    op.drop_table('widgets')
    op.drop_table('video_sections')
    op.drop_table('users')
    op.drop_table('themes')
    op.drop_table('testimonials')
    op.drop_table('team_members')
    op.drop_table('slides')
    op.drop_table('site_settings')
    op.drop_table('services')
    op.drop_table('projects')
    op.drop_table('pages')
    op.drop_table('menus')
    op.drop_table('contact_info')
    op.drop_table('categories')
    op.drop_table('about_sections')
    # ### end Alembic commands ###
