"""Remove body_heading_color column

Revision ID: 91b85bd79611
Revises: c310438a98d1
Create Date: 2025-02-20 10:48:19.002140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b85bd79611'
down_revision = 'c310438a98d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_dark_mode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('enable_animations', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('banner_bg_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('banner_title_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('banner_text_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('banner_button_bg_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('banner_button_text_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('banner_indicator_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('about_bg_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('about_title_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('about_text_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('about_stats_number_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('about_stats_text_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('about_box_bg_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('services_bg_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('services_title_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('services_card_bg_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('services_icon_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('services_card_title_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('services_card_text_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('blog_bg_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('blog_title_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('blog_card_bg_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('blog_date_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('blog_post_title_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('blog_excerpt_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('contact_bg_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('contact_title_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('contact_text_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('contact_form_bg_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('contact_button_bg_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('contact_button_text_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('video_bg_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('video_title_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('video_play_button_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('video_overlay_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('video_overlay_opacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('slider_height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('slider_transition_speed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('slider_animation_speed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('slider_is_autoplay', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('slider_show_arrows', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('slider_show_bullets', sa.Boolean(), nullable=True))
        batch_op.alter_column('logo_path',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('favicon_path',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('navbar_bg_color',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               nullable=True)
        batch_op.alter_column('navbar_text_color',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               nullable=True)
        batch_op.alter_column('navbar_active_color',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               nullable=True)
        batch_op.alter_column('navbar_hover_color',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               nullable=True)
        batch_op.alter_column('body_bg_color',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               nullable=True)
        batch_op.alter_column('body_text_color',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               nullable=True)
        batch_op.alter_column('body_link_color',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               nullable=True)
        batch_op.alter_column('primary_color',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               nullable=True)
        batch_op.alter_column('secondary_color',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               nullable=True)
        batch_op.alter_column('footer_bg_color',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               nullable=True)
        batch_op.alter_column('footer_text_color',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               nullable=True)
        batch_op.alter_column('footer_link_color',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               nullable=True)
        batch_op.drop_column('custom_meta_tags')
        batch_op.drop_column('meta_keywords')
        batch_op.drop_column('custom_footer_code')
        batch_op.drop_column('custom_header_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_header_code', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('custom_footer_code', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('meta_keywords', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('custom_meta_tags', sa.TEXT(), nullable=True))
        batch_op.alter_column('footer_link_color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('footer_text_color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('footer_bg_color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('secondary_color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('primary_color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('body_link_color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('body_text_color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('body_bg_color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('navbar_hover_color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('navbar_active_color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('navbar_text_color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('navbar_bg_color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('favicon_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('logo_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('slider_show_bullets')
        batch_op.drop_column('slider_show_arrows')
        batch_op.drop_column('slider_is_autoplay')
        batch_op.drop_column('slider_animation_speed')
        batch_op.drop_column('slider_transition_speed')
        batch_op.drop_column('slider_height')
        batch_op.drop_column('video_overlay_opacity')
        batch_op.drop_column('video_overlay_color')
        batch_op.drop_column('video_play_button_color')
        batch_op.drop_column('video_title_color')
        batch_op.drop_column('video_bg_color')
        batch_op.drop_column('contact_button_text_color')
        batch_op.drop_column('contact_button_bg_color')
        batch_op.drop_column('contact_form_bg_color')
        batch_op.drop_column('contact_text_color')
        batch_op.drop_column('contact_title_color')
        batch_op.drop_column('contact_bg_color')
        batch_op.drop_column('blog_excerpt_color')
        batch_op.drop_column('blog_post_title_color')
        batch_op.drop_column('blog_date_color')
        batch_op.drop_column('blog_card_bg_color')
        batch_op.drop_column('blog_title_color')
        batch_op.drop_column('blog_bg_color')
        batch_op.drop_column('services_card_text_color')
        batch_op.drop_column('services_card_title_color')
        batch_op.drop_column('services_icon_color')
        batch_op.drop_column('services_card_bg_color')
        batch_op.drop_column('services_title_color')
        batch_op.drop_column('services_bg_color')
        batch_op.drop_column('about_box_bg_color')
        batch_op.drop_column('about_stats_text_color')
        batch_op.drop_column('about_stats_number_color')
        batch_op.drop_column('about_text_color')
        batch_op.drop_column('about_title_color')
        batch_op.drop_column('about_bg_color')
        batch_op.drop_column('banner_indicator_color')
        batch_op.drop_column('banner_button_text_color')
        batch_op.drop_column('banner_button_bg_color')
        batch_op.drop_column('banner_text_color')
        batch_op.drop_column('banner_title_color')
        batch_op.drop_column('banner_bg_color')
        batch_op.drop_column('enable_animations')
        batch_op.drop_column('is_dark_mode')

    # ### end Alembic commands ###
