"""Add menu_title to Page model

Revision ID: 93da26dc1b72
Revises: 13cfc99c8ccb
Create Date: 2025-02-21 13:17:22.866815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93da26dc1b72'
down_revision = '13cfc99c8ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
