"""Update ContactInfo model and add page relationship

Revision ID: ac9c175aebc1
Revises: 93da26dc1b72
Create Date: 2025-02-21 15:54:55.060127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ac9c175aebc1'
down_revision = '93da26dc1b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('page_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_contact_info_page_id', ['page_id'])
        batch_op.create_foreign_key('fk_contact_info_page', 'pages', ['page_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('social_media')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_media', sqlite.JSON(), nullable=True))
        batch_op.drop_constraint('fk_contact_info_page', type_='foreignkey')
        batch_op.drop_constraint('uq_contact_info_page_id', type_='unique')
        batch_op.drop_column('page_id')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('instagram')
        batch_op.drop_column('twitter')
        batch_op.drop_column('facebook')

    # ### end Alembic commands ###
