"""Tema ayarları için yeni alanlar eklendi

Revision ID: c310438a98d1
Revises: 5af110fcf4be
Create Date: 2025-02-19 16:19:56.277980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c310438a98d1'
down_revision = '5af110fcf4be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
